### ISSUE TITLE
Add news page

### ISSUE THREAD

**Issue by GochoMugo** [forfuturellc/mmtc-ke#2]
A **news** page can be used to announce developments affecting the service, individual networks, etc.

Adding a news items should **not** warrant an app restart at all! Therefore, a remote data bucket should be used instead. This bucket may also be eventually be used for the actual data files in `data/`.

**Comment by BransonGitomeh** [comment]
what's your actual plan for this?...

**Comment by GochoMugo** [comment]
I have **not** thought of a specific implementation, actually. What would you suggest?

**Comment by GochoMugo** [comment]
**Implemented in v0.2.0**

**Comment by BransonGitomeh** [comment]
md, perfect :smirk:

**Comment by GochoMugo** [comment]
I am actually planning on moving the files from `web/_raw/` to `docs` so that they are readable through Github and the application. I really did **not** want to add databases or write HTML for this. Considering these documents may change rapidly, Markdown seems more manageable, don't you think?

**Comment by BransonGitomeh** [comment]
i totally agree, good work keeping the simplicity of the application, we should consider adding news for the upcomming features, maybe add disqus or facebook comments

**Comment by GochoMugo** [comment]
First, I dislike facebook, so **no** facebook here...

How about we add a link to view feature requests, say, https://github.com/forfuturellc/mmtc-ke/labels/feature%20request. This will help us avoid writing more code just to handle this use case. The same way, users may sign up in Disqus, let them sign up on Github and create an issue. Or send an email. What do you think?
