### ISSUE TITLE
add documentation

### ISSUE THREAD

**Issue by GochoMugo** [forfuturellc/mmtc-ke#9]
The documentation should lower the barrier to start contributing to the project. Topics include:

* [x] application architecture
* [x] collaboration
* [x] note on Code of Conduct
* [x] note on License, Contributing agreement
* [x] deployment information

**Comment by BransonGitomeh** [comment]
on deployment you can add an npm script  to do a push to openshift automatically kinda like this logger

https://github.com/BransonGitomeh/Genesis/blob/master/package.json#L9

**Comment by GochoMugo** [comment]
Am actually having [Travis CI](https://travis-ci.org/) deploy the application to OpenShift on commit on master branch. See in the configuration file: [`.travis.yml`](https://github.com/forfuturellc/mmtc-ke/blob/master/.travis.yml#L9) and [Openshift deployment on Travis CI](https://docs.travis-ci.com/user/deployment/openshift).

**Comment by BransonGitomeh** [comment]
deploy on commit :-| what happens when you commit incomplete stuff hah :-)

**Comment by GochoMugo** [comment]
We **NEVER** push to the **master** unless we are merging the **develop** branch, during a release.

**Comment by BransonGitomeh** [comment]
why don't you do feature branches which are merged after testing them you deploy after the merge...i see many projects doing that and seems to be quite cool and it works in a straightforward manner

**Comment by GochoMugo** [comment]
We use a git branching model similar to [this one](http://nvie.com/posts/a-successful-git-branching-model/).

**Comment by BransonGitomeh** [comment]
aah..i like PR's though...like work withing a pr in a branch for a feature, each major feature has a branch , but ill try to follow that

**Comment by GochoMugo** [comment]
**Added in v0.2.0**
